### PR TITLE
Require url to start with http://

### PR DESCRIPTION
**Pull request by amaury1093**

### CODE REVIEW

**Comment by tomusdrw** [comment]
What if the URL starts with `https`?

**Comment by amaury1093** [comment]
Does parity_dappsUrl always only return hostname:port? If yes I'd even make it simpler and only prepend http://.

If we do do a check, agreed. Probably something like if it has a protocol then leave it, else prepend http://

**Comment by tomusdrw** [comment]
Yes, but we should handle both `http` and `https` protocols - people can have a reverse proxy terminating ssl in front of the node and the ui should still work (see https://wallet.parity.io)

**Comment by amaury1093** [comment]
OK Makes sense. Changed in #7

**Pull request merged**
